# After doing:
#		git add .
#		git commit .
# do this command:
# 	make git
# this will create an updated 
#		.git/gitHeadInfo.gin
# from which the title page version info (Git Version) is taken
REMOTE='184.169.244.79:~/Prof/wp-content/uploads/archive/Slides/'
CHP=chp4
$(CHP).pdf : *.tex
	pdflatex $(CHP); \
	pdflatex $(CHP); \
	pdflatex $(CHP);
git: $(CHP).tex
	pdflatex $(CHP); \
	pdflatex $(CHP); \
	git add .; \
	git commit .; \
	.git/hooks/post-checkout; \
	pdflatex $(CHP);
	pdflatex $(CHP);
	git push;
upload:
	rsync -avz -e 'ssh -l ec2-user' chp[0-9].pdf $(REMOTE)
all:
	pdflatex chp0.tex
	pdflatex chp1.tex
	pdflatex chp2.tex
	pdflatex chp3.tex
	pdflatex chp4.tex
	pdflatex chp5.tex
	pdflatex chp6.tex
	pdflatex chp7.tex
	pdflatex chp8.tex
	pdflatex chp9.tex
